<a href="https://colab.research.google.com/github/Vanshita613/python-practice/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


**SERIES**

In [ ]:
import pandas as pd

x=[2,4,5,]

y = pd.Series(x,index=['a','s','d'],dtype="float",name="python")

print(y)
print(type(y))

a    2.0
s    4.0
d    5.0
Name: python, dtype: float64
<class 'pandas.core.series.Series'>

In [ ]:
info ={ "name":['sia','sam','john','v'] , "subj":['python','AI','java','numpy'],"rank":[1,2,3,4]}

var1=pd.Series(info)

var1

name          [sia, sam, john, v]
subj    [python, AI, java, numpy]
rank                 [1, 2, 3, 4]
dtype: object

In [ ]:
s = pd.Series(7)

print(s)

0    7
dtype: int64

**DATAFRAME**

In [ ]:
import pandas as pd

list=[2,4,6,4,7,9]

var=pd.DataFrame(list)

var

   0
0  2
1  4
2  6
3  4
4  7
5  9

In [ ]:
dict ={
    "a":[1,2,3,4,4],
    "b":[1,2,3,4,5]
    }
var1=pd.DataFrame(dict)
var1

   a  b
0  1  1
1  2  2
2  3  3
3  4  4
4  4  5